name: CI
on:
  push:
    branches:
      - main
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - run: cd functions && yarn && cd ..
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --project bioforest-smart
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BIOFOREST_SMART }}
          FIREBASE_PROJECT: bioforest-smart
