name: CI
on:
  push:
    branches:
      - main
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - run: cd functions && yarn && cd ..
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project bioforest-smart
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: bioforest-smart
